### ISSUE TITLE
Step 5 - Cloud Shell Script Error : Rerun script?

### ISSUE THREAD

**Issue by richross** [microsoft/Azure-Analytics-and-AI-Engagement#107]
Hello!  Doing the deployment in our tenant.  Ran the cloud shell script and it failed for me in the power bi reports step.  My guess is because of permissions on the PBI side.  

My question is can I just rerun the script?  Will it handle that there are items already configured in the tenant or do I need to reset back to some previous state in the environment?

Thanks!

**Comment by xor-ranavikrant** [comment]
If you let the script execute to completion, even with error's in power BI it should have completed rest of the set up. You will just have to manually upload the power BI reports and update the connections. If you rerun the script it will give errors of objects already existing.
