### ISSUE TITLE
PowerBI Embedded Steps Missing

### ISSUE THREAD

**Issue by alxdean** [microsoft/Azure-Analytics-and-AI-Engagement#109]
Hi, the App tries to load multiple visuals from the workspace. But nowhere do you actually mention that either PBI Embedded or a Dedicated Premium Capacity is required for the demos to fully function. You do have some instructions on how to allow the Service Principal to access PBI, but nowhere actually point out that it's a prerequisite. No biggie. added it manually and updated the workspace to run on embedded, but might be good to include in the Setup readme.

**Comment by xor-ranavikrant** [comment]
Thanks for the feedback. Updated requirement section for clearer instructions.
