### ISSUE TITLE
FSI:  suggest git shallow clone

### ISSUE THREAD

**Issue by larryclaman** [microsoft/Azure-Analytics-and-AI-Engagement#112]
in the FSI branch, the readme-shell.md file suggests cloning the repo as `git clone -b fsi https://github.com/microsoft/Azure-Analytics-and-AI-Engagement.git fsi`.  However, this repo is HUGE.  I suggest the git command be modified to use a shallow clone as follows:
```
git clone -b fsi   -–depth 1 --single-branch https://github.com/microsoft/Azure-Analytics-and-AI-Engagement.git fsi
```
This will drastically reduce the size of the repo being pulled down.

**Comment by xor-ranavikrant** [comment]
Thanks for the suggestion. We have updated the instructions :)
