### ISSUE TITLE
Errors running healthcareSetup.ps1

### ISSUE THREAD

**Issue by NigelDW-ND** [microsoft/Azure-Analytics-and-AI-Engagement#116]
Hi Team,

I've been trying to deploy this for 3 days on a bunch of different regions, I however can only get this far.

Any ideas?

![image](https://user-images.githubusercontent.com/57714390/169488481-31ad6d9b-4389-46b3-9637-9606c3c0c3cd.png)

**Comment by xor-ranavikrant** [comment]
Looks like there was issue in uploading cosmos data. Let the script complete execution and later try to execute the cosmos subscript. This should not affect the overall deployment except the htap reports. We will check at our end to see if we can reproduce the issue.

**Comment by xor-ranavikrant** [comment]
We have fixed the issue with data file. You can clone the repo again and just execute the cosmos subscript if you have the environment previously deployed still running.
