### ISSUE TITLE
QnA Maker service discontinuity issue- CognitiveServices

### ISSUE THREAD

**Issue by Cloud2023** [microsoft/Azure-Analytics-and-AI-Engagement#118]
getting error in retail demo 2.0 ARM template execution

{"code":"InvalidTemplateDeployment","details":[{"code":"SpecialFeatureOrQuotaIdRequired","message":
"The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'QnAMaker' ."}],
"message":"The template deployment 'Microsoft.Template-20221230184804' is not valid according to the validation procedure. 
The tracking id is '923442df-3ed8-4bb2-bdac-392704acff67'. See inner errors for details."}

execution of ARM templates in step 3 of below URL
https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/blob/retail2.0/retail/Readme-shell.md

**Comment by xor-ranavikrant** [comment]
Template has been updated to remove the obsolete services. Thanks.
