### ISSUE TITLE
analytics-in-midp setup error

### ISSUE THREAD

**Issue by alxdean** [microsoft/Azure-Analytics-and-AI-Engagement#119]
Hi folks, 
Firstly, the setup readme does not cover following parameters:
app_midpdemo_name
asp_midpdemo_name

Secondly the /home/dev/midp/ddib/midpSetup.ps1 script fails pretty fast with:

New-AzResourceGroupDeployment: /home/dev/midp/ddib/midpSetup.ps1:251
Line |
 251 |  New-AzResourceGroupDeployment -ResourceGroupName $rgName `
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 2:03:45 PM - Error: Code=InvalidTemplateDeployment; Message=The template deployment 'mainTemplate' is not valid according to the validation procedure. The tracking id is 'dfc8f738-b598-42df-b51c-258d07348e55'. See inner errors
     | for details.

any ideas?

**Comment by xor-ranavikrant** [comment]
Thank you for the feedback. We have updated the details. Please use https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/tree/midp-with-cosmos branch for a more UI based experience for template deployment.
