### ISSUE TITLE
Fabric Dream Demo app-fabric WebApp Not loading content

### ISSUE THREAD

**Issue by jmace-cdw** [microsoft/Azure-Analytics-and-AI-Engagement#133]
Followed the tutorial on setup of the Fabric Dream Demo.  Deployment was failing several times when deploying the reports.  
New-PowerBIReport commands.  Commented this out for use with service principal in line 502 of the fabricsetup.ps1 script
and worked around it by calling "Connect-PowerBIAccessToken" before execution.

Upon completion reports and other content are verified to be working in the Fabric Workspace area; however, the WebApp for the demo is not loading several content pages including the World Map, Tile 8 Introduction to Fabric, Tile 14 Sales Performance, Tile 15 Finance Revenue and Profitability, Tile 16 Marketing campaign and Analytics, Tile 17 Employee Analytics, Tile 18 Operations - Warehouse Operations, Tile 19 IT operations, Tile 20 Sales Event Video, Tile 21 CDO Metrics Video fails to load, Tile 22 Executive Dashboard, and Tile 24 Video.

Finally, the KQL demo setup is failing when registering the event hub feeds in the Fabric UI.

We have an upcoming demo with a customer and need these issues resolved to deliver a good impacting demo and presentation.  Please advise on resolution.

**Comment by xor-ranavikrant** [comment]
Since you have modified the Power BI section, it seems the report id's were not replaced correctly in the web app's configuration. You can edit the config of the web app and replace the respective report id's in it. Reach out to dreamdemos@microsoft.com for faster response.

**Comment by jmace-cdw** [comment]
@xor-ranavikrant  We've been able to pinpoint the issue.  It was due to lack of the setting on the fabric tenant to allow the service principal.  Documentation can be found here:  https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal

Thanks for your response.

**Comment by xor-ranavikrant** [comment]
Great to hear. The info is also available in our prerequisites and faqs. Feel free to refer to them.
https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/blob/main/Manufacturing/Power%20BI%20Embedding.md
https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/blob/main/Manufacturing/F.A.Q.md#what-if-embedded-reports-dont-show-up-in-web-app
