### ISSUE TITLE
Twitter Real-Time Report Failing

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#17]
Azure Function is working.

![image](https://user-images.githubusercontent.com/2984187/88818527-7d5a7a00-d1c7-11ea-83a2-0ae527a27229.png)

Event Hub is in good shape.

![image](https://user-images.githubusercontent.com/2984187/88818635-95ca9480-d1c7-11ea-9667-891bc0b47dfd.png)

ASA output is observed.

![image](https://user-images.githubusercontent.com/2984187/88818713-ada21880-d1c7-11ea-96d6-9cb7882a02bc.png)

Power BI Output in ASA shows no workspace assigned, but...

![image](https://user-images.githubusercontent.com/2984187/88818774-c14d7f00-d1c7-11ea-98b2-89340af9ecfe.png)

When listed in Power BI Desktop the dataset shows up in the CDP workspace, with no Owner.

![image](https://user-images.githubusercontent.com/2984187/88819014-15f0fa00-d1c8-11ea-8ecf-151f28ba9df4.png)

Once the config values and keywords for Azure Functions were filled in with twitter developer account credentials it all started to work. Data was visible on the map in Power BI.

![image](https://user-images.githubusercontent.com/2984187/88818904-f063f080-d1c7-11ea-9a1e-ea40b667733b.png)

The disconnected path did not work during QA.

**Comment by xor-ranavikrant** [comment]
Twitter function build updated for fixing this issue in the attached pull request @daronyondem
