### ISSUE TITLE
Power BI Linked Services is missing in Synapse Workspace

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#18]
Since we removed the step of creating new workspace in Power BI, the workspace name is not in our control anymore. So linked service creation for Power BI in synapse workspace is failing.

**Comment by daronyondem** [comment]
I can see the reports in Synapse.

![image](https://user-images.githubusercontent.com/2984187/88844874-01265d80-d1ec-11ea-90ec-ff9b57c03571.png)

What do you think the broken linked service is affecting?

**Comment by daronyondem** [comment]
@xor-ranavikrant Bump

**Comment by xor-ranavikrant** [comment]
We are going over the test cycle again. I found this as potential issue by looking at the code. Will update if we run into it again.

**Comment by daronyondem** [comment]
I just did another deployment. No issues so far. 

![image](https://user-images.githubusercontent.com/2984187/88906399-12a94d00-d260-11ea-815d-c9c4822e1bcb.png)

I will try CloudLabs environment too.

**Comment by xor-ranavikrant** [comment]
We tried with cloud labs. Does not seem to be recurring. Closing this for now.
