### ISSUE TITLE
Static Power BI Reports did not get uploaded

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#19]
Static Power BI reports did not upload to the pre-created workspace during the testing. This part was working before the fix for multiple workspaces was added.

**Comment by daronyondem** [comment]
This worked during my testing today. Here is a custom workspace I created and all reports were added.

![image](https://user-images.githubusercontent.com/2984187/88839386-a7219a00-d1e3-11ea-81f6-7bd7f7a32761.png)

I will check this again on the next QA round. Do you have any further information about the issue?

**Comment by daronyondem** [comment]
I just did another deployment and reports are in the environment.

![image](https://user-images.githubusercontent.com/2984187/88906237-dd046400-d25f-11ea-937e-5e32eae14041.png)

Next, I will try with CloudLabs

**Comment by xor-ranavikrant** [comment]
We tried it with CloudLabs again. Doesn't seem to be recurring. Closing This for now.
