### ISSUE TITLE
Combine Separate ARM Templates

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#2]
Hi @xor-ranavikrant

Can you merge the twitter ARM template with the primary ARM template? We have to give users a single ARM template to deploy. Otherwise, they will have to go through multiple steps. Please push the changes into the `real-time` branch.

Thanks

**Comment by xor-ranavikrant** [comment]
The templates have been merged. Will delete the extra files if they are causing confusion.

**Comment by daronyondem** [comment]
Please do not close issues without mutual approval.

We can close this issue when the leftover files are deleted.

**Comment by xor-ranavikrant** [comment]
Have deleted the extra file. Please review and close.

**Comment by daronyondem** [comment]
Thanks!
