### ISSUE TITLE
Changes to be made in Before-Starting.md

### ISSUE THREAD

**Issue by SomyKamble** [microsoft/Azure-Analytics-and-AI-Engagement#20]
Hello Team 

I request you to please address the following things with respect to "Before-Starting.md" markdown

- 	While creating Power BI Streaming dataset, please mention below point at step 4, not at step 5:“Make sure Historic data analysis is enabled. Select Create to proceed”
- 	Create Resource Group step is not needed for Demo Champs as resource group is already packaged with the lab environment.
- 	While creating Azure Synapse Analytics workspace, in the custom deployment form, password rules and unique suffix rules has  to be mentioned clearly else deployment will fail.
- 	At Download artifacts step, while launching cloud shell, entire step to create storage account has to be added in the document. PFB screenshot  link  [screenshot](https://netorgft3817606-my.sharepoint.com/:f:/g/personal/somy_kamble_salespointinc_com1/Ei7D79EMbKlItJsTMmDuaqsByhJOuC_EWHNgLTfdw8wvDA?e=EE7llU) your reference: 
- 	Mention storage account name and file share name to be unique names in the above step.
- 	Please remove unnecessary step from Power BI part related to two workspaces.

**Comment by daronyondem** [comment]
Hi @SomyKamble 

- I have removed step 5 from Task 1 and made it part of step 4.
- Cloudlabs warning for resource group creation is added.
- Password policy and unique suffix requirements added.
- Cloud Shell Storage dependency clarifications added.
- Multiple workspaces requirement is removed.

Thanks for your feedback.
