### ISSUE TITLE
HOL-step-by-step: Task 1 Step 10-11

### ISSUE THREAD

**Issue by shashankkhedikar** [microsoft/Azure-Analytics-and-AI-Engagement#22]
![image](https://user-images.githubusercontent.com/10440963/88868675-a712a180-d1c5-11ea-9022-0fa6c2b37da7.png)

**Comment by daronyondem** [comment]
HOL Updates and QA is in the backlog. I'm moving this back to the backlog as we are not planning this to fix before Friday's release.
