### ISSUE TITLE
Deployment failed - could not provision Synapse workspace

### ISSUE THREAD

**Issue by joelhulen** [microsoft/Azure-Analytics-and-AI-Engagement#24]
Selected the `eastus` location in the ARM template deployment form. Error returned:

```
{
    "error": {
        "code": "ValidationFailed",
        "message": "Workspace request validation failed, check error details for more information",
        "details": [
            {
                "code": "SqlServerRegionDoesNotAllowProvisioning",
                "message": "Location '' is not accepting creation of new Windows Azure SQL Database servers at this time."
            }
        ]
    }
}
```

![image](https://user-images.githubusercontent.com/5950304/88879432-3df85180-d1f8-11ea-8ca8-15e31e18307e.png)

**Comment by joelhulen** [comment]
I tried a different location (`westcentralus`) and received the same error.

**Comment by daronyondem** [comment]
I was having the same issue on my end as well. I started creating a QnA document here https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/blob/main/CDP-Retail/QnA.md Not precisely the fix for this particular issue but might be helpful for someone else.

**Comment by daronyondem** [comment]
This is now fixed.
