### ISSUE TITLE
Data Source Authentication issue in Power BI

### ISSUE THREAD

**Issue by KmrShiv** [microsoft/Azure-Analytics-and-AI-Engagement#28]
![Power BI](https://user-images.githubusercontent.com/69001915/88930986-e1e60980-d299-11ea-9496-43a83e37a278.PNG)

**Comment by daronyondem** [comment]
What is the issue? This is expected and there are instruction in the setup guide that needs to be implemented to fix it.

**Comment by xor-ranavikrant** [comment]
This is the state after running the automation

**Comment by daronyondem** [comment]
Just did a new deployment and can't repro the issue.

![image](https://user-images.githubusercontent.com/2984187/88946773-528c2680-d298-11ea-99bb-195b3d63ea54.png)

Can you give it another shot?

**Comment by daronyondem** [comment]
Any updates @KmrShiv ?

**Comment by daronyondem** [comment]
@mithilyadav22 can you check with @KmrShiv if this is still an issue? I guess he is not monitoring issues they submitted here.
