### ISSUE TITLE
'customcsv' ADLS container is missing in Azure Synapse Workspace

### ISSUE THREAD

**Issue by KmrShiv** [microsoft/Azure-Analytics-and-AI-Engagement#29]
![Synapse Adls](https://user-images.githubusercontent.com/69001915/88931359-5b7df780-d29a-11ea-9c64-dc7e3cdc6669.PNG)

**Comment by daronyondem** [comment]
Is this in CloudLabs? I don't see the issue in regular subscriptions?

**Comment by daronyondem** [comment]
Any updates @KmrShiv ?

**Comment by daronyondem** [comment]
@mithilyadav22 can you check with @KmrShiv if this is still an issue? I guess he is not monitoring issues they submitted here.
