### ISSUE TITLE
Combine Powershell Scripts

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#3]
Right now we have two PowerShell scripts the user has to run. Can we combine the two? Any particular reason we keep those separate?

![image](https://user-images.githubusercontent.com/2984187/88041975-ddac4480-cb53-11ea-80fe-61eb23f3803a.png)

Thanks

**Comment by xor-ranavikrant** [comment]
Hi Daron. I have already combined both the scripts and ARM templates.The external files can be deleted ive moved that code as well as template json into the core json file. Will delete the two extra files if they are causing confusion.

**Comment by daronyondem** [comment]
Please do not close issues without mutual approval. 

We can close this issue when the leftover files are deleted.

**Comment by xor-ranavikrant** [comment]
Have deleted the extra file. Please review and close.

**Comment by daronyondem** [comment]
Thanks!
