### ISSUE TITLE
'Reset' SQL Script is missing in Azure Synapse Workspace

### ISSUE THREAD

**Issue by KmrShiv** [microsoft/Azure-Analytics-and-AI-Engagement#30]
![Reset SQL Script In Synapse](https://user-images.githubusercontent.com/69001915/88931578-a4ce4700-d29a-11ea-8525-abff869f3391.PNG)

**Comment by daronyondem** [comment]
That script was just for the demo. It was not planned to be included into the automation. Is there a new decision?
