### ISSUE TITLE
Pipelines (Customize Campaign Analytics,Customize Decomposition Tree..etc) are getting failed in Synapse workspace

### ISSUE THREAD

**Issue by KmrShiv** [microsoft/Azure-Analytics-and-AI-Engagement#34]
Error Message 1 : Operation on target Clean Social Analytics failed: ErrorCode=AkvAccessDeniedByCallerNotAuthorized,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Caller was not found on any access policy in this key vault, secretName: SQL-USER-ASAEXP, secretVersion: , vaultBaseUrl: https://asaexpkeyvaultkmrshiv.vault.azure.net/. The error message is: The user, group or application 'appid=eaa407dd-5141-4b77-9d35-1eae315adde9;oid=fefdf081-c176-418f-8ab3-1764a790cd1d;iss=https://sts.windows.net/f94768c8-8714-4abe-8e2d-37a64b18216a/' does not have secrets get permission on key vault 'asaexpkeyvaultkmrshiv;location=westus2'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287.,Source=Microsoft.DataTransfer.ClientLibrary,'

Error Message 2: "errorCode": "2200", "message": "ErrorCode=SqlOperationFailed,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=A database operation failed. Please search error to get more details.,Source=Microsoft.DataTransfer.ClientLibrary,''Type=System.Data.SqlClient.SqlException,Message=PdwManagedToNativeInteropException ErrorNumber: 46724, MajorCode: 467, MinorCode: 24, Severity: 20, State: 2, Exception of type 'Microsoft.SqlServer.DataWarehouse.Tds.PdwManagedToNativeInteropException' was thrown.,Source=.Net SqlClient Data Provider,SqlErrorNumber=100000,Class=16,ErrorCode=-2146232060,State=1,Errors=[{Class=16,Number=100000,State=1,Message=PdwManagedToNativeInteropException ErrorNumber: 46724, MajorCode: 467, MinorCode: 24, Severity: 20, State: 2, Exception of type 'Microsoft.SqlServer.DataWarehouse.Tds.PdwManagedToNativeInteropException' was thrown.,},],'", "failureType": "UserError", "target": "Ingest Social Analytics", "details": [] }

**Comment by daronyondem** [comment]
Customize Campaign Analytics and Customize Decomposition Tree are now fixed.
