### ISSUE TITLE
Power BI streaming dataset (Tweetsout) missing

### ISSUE THREAD

**Issue by joelhulen** [microsoft/Azure-Analytics-and-AI-Engagement#37]
The setup completed successfully. However, in Task 10, Step 4, I do not see the streaming dataset named `Tweetsout`:

![image](https://user-images.githubusercontent.com/5950304/88949446-3d47d580-d261-11ea-8428-489a3cf877c0.png)

**Comment by daronyondem** [comment]
Sometimes it takes a while for it to show up and the function feed in data. That real-time dataset is created when the function app pushes data. Can you give it another shot and let me know what you see?

**Comment by joelhulen** [comment]
Still not seeing it. The Stream Analytics job is running, but no events are coming in from Event Hubs. When I look at Event Hubs, I see requests incoming, but no messages.

**Comment by daronyondem** [comment]
Were you able to test this with the latest automation changes? Any updates @joelhulen

**Comment by joelhulen** [comment]
This worked after redeploying to a new resource group.
