### ISSUE TITLE
Hard-coded resourcegroup Name

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#4]
User will need to use same subscription for sharing the automation with demo personnel, it would be better if we accept the resource group name from user in the script instead of the hardcoded wildcard that we currently have in the core script._( 01-environment-setup.ps1 line number 83)_

**Comment by daronyondem** [comment]
This is now complete. There is a resource group selection during automation now.

![image](https://user-images.githubusercontent.com/2984187/88700478-6c4f3180-d111-11ea-8679-1fa1258f301a.png)

Looking forward to your approval to close the issue.

**Comment by daronyondem** [comment]
@xor-ranavikrant bump

**Comment by xor-ranavikrant** [comment]
Thank you Daron. I Have verified this. Closing the issue.

**Comment by xor-ranavikrant** [comment]
The if() condition on line number 85 does not have an else block. So if the statement finds a single resource group it does not assign a resource group name to the variable, which in turn causes the failure on line 96.

**Comment by daronyondem** [comment]
Good catch!

**Comment by xor-ranavikrant** [comment]
Are you fixing this at your end or should i make a fix for this in main branch @daronyondem

**Comment by daronyondem** [comment]
Your branch is merged and deleted. Feel free to create a new one from master. 

You can always pick any of the issues if you have the time to help. Just make sure you self-assign it so that we don't end up having multiple people working on the same issue.

Thanks Ranavikrant.

**Comment by xor-ranavikrant** [comment]
Sure, Have created a pull request for this fix
