### ISSUE TITLE
No restriction on unique Suffix

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#5]
When user enters uniqueSuffix while deploying the ARM template there is no restriction on this field. Since this suffix is appended to the names of all the resources, the template may fail if used enters uniqueSuffix with a special character or a capital letter as storage account names will not accept anything except lower case characters.

**Comment by daronyondem** [comment]
Now that we have instructions about the rules for the suffix I don't think we have to implement this. Would you agree @xor-ranavikrant ?

**Comment by xor-ranavikrant** [comment]
Yes, since we have added the clauses in the document I'll go ahead and close this.
