### ISSUE TITLE
All CSV files in 'customcsv' ADLS container need to be update in ARM template from Solliance Synapse Workspace.

### ISSUE THREAD

**Issue by KmrShiv** [microsoft/Azure-Analytics-and-AI-Engagement#53]
![WWI](https://user-images.githubusercontent.com/69001915/89280097-c433ee00-d665-11ea-8b68-8d3e2421afcc.PNG)

**Comment by daronyondem** [comment]
CSV files are not in the ARM template. 

I don't understand the request. Can you be more specific?

Thanks

**Comment by KmrShiv** [comment]
In After scenario ,we have triggered the master pipeline during the testing. But In Power BI reports data were getting mismatched. We have deployed the all Azure resources using Azure Deploy Link. That why i am asking you to update csv file from 'customcsv' container Solliance Synapse workspace.

**Comment by KmrShiv** [comment]
I think ,you should update the powershell code.

**Comment by daronyondem** [comment]
Hi @KmrShiv 

Why do you think I should update the PowerShell code?

Copying all files from Solliance Synapse workspace has caused issues in the past. I need to understand what specific files have to move to be able to limit QA to only those files.  Can you describe the steps you took to fix the issue after you deployed a new environment with the Azure Deploy Link?

Thanks

**Comment by KmrShiv** [comment]
Why do you think I should update the PowerShell code? : 'I think, @Mithil/@Rana is best person to answer this .' 
You can download the highlighted csv files from 'customcsv' container in folder 'Manufacturing Scenario Dataset' solliance Synapse workspace.
![csv files](https://user-images.githubusercontent.com/69001915/89399760-85b73580-d730-11ea-9323-e414ea973360.PNG)

**Comment by daronyondem** [comment]
Hi @KmrShiv 

I would kindly ask you to put additional time into crafting your messages sent on Github. I'm having a hard time understanding your messages. The @ mentions that you added are malformed. Therefore the right people will not get a notification. 

`Manufacturing Scenario Dataset` folder that you pointed out is not used by a pipeline or a script. It was just uploaded for the show. If this is the only folder you need to be copied over, that is easy and does not require QA. Just to double-check, is `Manufacturing Scenario Dataset`  the only folder you want to be copied?

**Comment by mithilyadav22** [comment]
Hi @daronyondem ### Just to double-check, is Manufacturing Scenario Dataset the only folder you want to be copied? Yes please copy all the CSVs from Manufacturing folder

**Comment by daronyondem** [comment]
Done
