### ISSUE TITLE
Power BI and Synapse authentication not working with vm identity tokens

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#54]
Tokens taken from az login --identity return unauthorized for synapse and Power BI api's

**Comment by daronyondem** [comment]
Hey @xor-ranavikrant I have created a separate project for manufacturing here https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/projects/2 Feel free to move issues to the appropriate columns on the kanban board ;)

**Comment by xor-ranavikrant** [comment]
Added AZ credentials in input for logging in instead of logging in with identity
