### ISSUE TITLE
Twitter ConsumerKeySecret Value Missing Error

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#6]
After deployment I tried hitting the endpoint. Got the error below.

![image](https://user-images.githubusercontent.com/2984187/88216199-741c5b00-cc65-11ea-8a08-6cd1ff95756c.png)

I checked the config for the function app, it looks like the values are in there.

![image](https://user-images.githubusercontent.com/2984187/88216279-93b38380-cc65-11ea-8260-e93cc6d7123c.png)

Any ideas?

**Comment by xor-ranavikrant** [comment]
Updated the build shared by santosh. That should fix this error. Please review and close.
