### ISSUE TITLE
Power BI datasets api throwing 404(https://api.powerbi.com/v1.0/myorg/groups/$wsid/datasets/$dataSetId/Default.UpdateDatasources)

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#63]

**Comment by daronyondem** [comment]
What's the body you used? The content of the body has to match one to one to the current values available in the environment for the update to work. It is frustrating, but it is what it is :(

**Comment by xor-ranavikrant** [comment]
@daronyondem  could you take a look if we are missing something in the code, not able to figure out the problem. Here is the [file](https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/blob/real-time/Manufacturing/automation/manufacturingSetup.ps1). Code block at line 500 (uploading report) and  582(updating dataset connection)

**Comment by daronyondem** [comment]
The source parameters have to match the current values assigned in the report. Otherwise, it gets rejected all the time.

**Comment by xor-ranavikrant** [comment]
The API does work now after changing its original source parameters but after the updation the report shows following message:
![image](https://user-images.githubusercontent.com/33507675/90728369-6a2c5d00-e2e2-11ea-988a-88459ebc43fb.png)
Is there something else to be done to authenticate the report by default or user has to re-enter the username and password.?

**Comment by daronyondem** [comment]
In the case of Retail, I was taking the user through the authentication manually. 

![image](https://user-images.githubusercontent.com/2984187/90786154-e5eecf80-e30b-11ea-8f48-2e5420971ba5.png)

I was not able to find an API where we could automate this step.
