### ISSUE TITLE
Converting WWI Manufacturing Website from aks to App service

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#64]

**Comment by daronyondem** [comment]
- Needs to be converted into a single web app.
- iFrame links, reportIds, and dashboardIds have to be configurable.
- All external resources have to be configurable.
- Gather all videos and images, if files are larger than 100MBs hand it over to @daronyondem to upload it to solliance subscription.

**Comment by daronyondem** [comment]
Waiting for @alizohaib to give a status update.

**Comment by daronyondem** [comment]
As an additional request, we need the powerapp page configurable as well. Users will create their powerapp manually and will need to configure their web site based on that. 

Check #73 for background.

**Comment by alizohaib** [comment]
@daronyondem The powerapp page and other page-ids are all configurable through the config file now.

**Comment by alizohaib** [comment]
Apparently, this repo https://dev.azure.com/daidemos/ManufacturingDemo-Web/_git/ManufacturingDemo-Web is the retail demo which was incorrectly named. So my last comment was about this one.

**Comment by xor-ranavikrant** [comment]
@alizohaib @santosh-3e  The web app does not seem to be picjing up the values from config.js Please advise

**Comment by santosh-3e** [comment]
I had asked Ali to make it using .env file or configurable which is not required to be re-build.  @alizohaib let us know why this is still coming from config.js file.

**Comment by alizohaib** [comment]
@santosh-3e React doesn't have runtime environment variables. Hence, I have used config.js so that we don't have to build it every time but editing the config.js and restarting the app would load the variables. 
@xor-ranavikrant Can you let me know what you edited and if you restarted the app or not. Thanks.

**Comment by xor-ranavikrant** [comment]
Yes @alizohaib  I changed the blob url to point to the updated environment but that did not workout even after restarting the app.You may have to use .env file or an external Json config.

**Comment by alizohaib** [comment]
Can you paste the new blob url here. Let me also check.

**Comment by alizohaib** [comment]
I just checked. Edit this file like in the screenshot. It is updating accordingly. 
![image](https://user-images.githubusercontent.com/26845129/91323738-a9731600-e7da-11ea-9419-f04b59fc0e20.png)

**Comment by xor-ranavikrant** [comment]
Its working now. Tried a different browser, might have been a caching issue. Thanks.Please provide @santosh-3e  with latest code changes so he may work on the back end code.

**Comment by alizohaib** [comment]
@xor-ranavikrant Can we please have an internal repository for this. It will be very time consuming to send/receive zip files.

**Comment by santosh-3e** [comment]
Everything is configured and app is working properly.
