### ISSUE TITLE
Packaging the wideworldimporters webapp

### ISSUE THREAD

**Issue by xor-ranavikrant** [microsoft/Azure-Analytics-and-AI-Engagement#65]
Source Code/Publishing details required

**Comment by daronyondem** [comment]
@RonStoehr Can you loop in Nikhil?

**Comment by RonStoehr** [comment]
Sent email to Nikhl -- he may still need to accept his invite so he is able to be assigned issues.

**Comment by xor-ranavikrant** [comment]
I have searched out the publish for this web app. Assuming nothing needs to be made configurable in this and moving forward with it.
