### ISSUE TITLE
Automate creating and initial import of all tables

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#66]
All tables from original SQL Pool will be created as part of the automation and their data will be populated as well. Data from the original environment can be exported with temporary pipelines into a CSV file into the data lake. Once these files are ready please let me know so that we can move the original CSV files into permanent storage (solliance storage account). Automation script will use CSV files from solliance storage account to load into tables during automation.

**Comment by KmrShiv** [comment]
why do you want to import all tables from original SQL pool in csv files?

**Comment by daronyondem** [comment]
We will host the CSV files in solliance storage and use the automation script to load CSV files into tables. That's the exact same process we used in retail.

**Comment by xor-ranavikrant** [comment]
https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/files/5103153/WWI.App.Powerbi.Resources.xlsx
This might help finding the relevant tables @KmrShiv

**Comment by daronyondem** [comment]
Meeting note from 8/24
This is now waiting for #80 to be completed.

**Comment by RonStoehr** [comment]
Abhishek Mishra will research which reports are needed
