### ISSUE TITLE
Clarification about the function of all the containers and files in the data lake from Santosh, Sanket, Ronen, Tarun

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#67]

**Comment by daronyondem** [comment]
@santosh-3e

**Comment by sanket-t-shah** [comment]
Storage Account   Name | Container Name | To Include | Copy Data | Purpose
-- | -- | -- | -- | --
manufacturingdemo12 | mfg-historical-data | Yes | Yes | Original Source Files for Cosmos Data
manufacturingdemo12 | mfgoutputs | Yes | No | IoT Hub Streaming Source. Need only this container to be created.

**Comment by sanket-t-shah** [comment]
We are not sure about Cosmos DB Export stored in mfgcosmos container. This has a large 26+ GB Export of Cosmos. needs more clarification from folks.

**Comment by daronyondem** [comment]
Who exactly? :) We might need to mention their names so that they can receive e-mail notifications about the issue and respond.

**Comment by sanket-t-shah** [comment]
Data Science Dojo team - let's check with them. @santosh-3e / Shiv - any insights on this if you've worked on?
