### ISSUE TITLE
Discuss packaging options for ML studio and its assets

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#68]

**Comment by daronyondem** [comment]
- Are the notebooks in the synapse environment the only resources we should be worried about in the context of the Azure ML service?
- What are the resources used by the notebooks?

**Comment by daronyondem** [comment]
Three notebooks showcased in the demo video.

![image](https://user-images.githubusercontent.com/2984187/90706099-14819180-e29d-11ea-9a4c-464d6db3fb62.png)

**Comment by tshrivasdsd** [comment]
- We have 4 Azure Synapse AI/ML notebooks that are part of the MFG demo and have also been included in the DEMO SCRIPT.  

- I am sharing the screen-shot ( please refer to the thicker box in red)

![image](https://user-images.githubusercontent.com/46974755/90806870-7b6d6d80-e2d2-11ea-8609-6c93c11d095d.png)

**Comment by tshrivasdsd** [comment]
- We have 10 Azure ML notebooks that are part of the MFG demo and they have been included in the DEMO SCRIPT.
- I am sharing two screen-shots here ( 1. for how to reach to the correct folder 2. for a snapshot of all the notebooks, under the folder) 
  
 **Screenshot 1**: Folder  
![image](https://user-images.githubusercontent.com/46974755/90807386-4281c880-e2d3-11ea-8e47-fad2f027a701.png)

**Screenshot 2:** Notebooks
![image](https://user-images.githubusercontent.com/46974755/90807586-8b398180-e2d3-11ea-88f3-b2361bd2596d.png)
