### ISSUE TITLE
Cross-Check if any of the reports are missing

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#72]

**Comment by daronyondem** [comment]
Reports found in the demo video.

- Miami Factory Report
- Equipment View Report
- CNC Machine Issue View
- Product Defect Rate Spike Report
- Production Quality Degradation report
- Azure Synapse Link Report
- Campaign Report
- Worker Safety and Product Quality Report
- Global Occupational Safety Report
- Incident Report Search
- 7a Production Quality
- 1 Billion Rows

**Comment by xor-ranavikrant** [comment]
Azure Synapse Link Report not a part of scope
