### ISSUE TITLE
Discuss packaging options for powerapps

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#73]

**Comment by SridharTerawe** [comment]
For the Manufacturing Demo. Please clarify are we explaining the process to package the powers apps within Web App application for the customer demos or are we trying to explain the packaging process for the customer to work with his data and mention steps to package the power app contents for the customer data. Please clarify here to discuss in the 9am call tomorrow.

**Comment by daronyondem** [comment]
We are looking to understanding how we can deploy it on behalf of the customer during the automation script. Does this make sense?

**Comment by SridharTerawe** [comment]
Sure, go it.  I will do a detailed write up on this.

Thanks,
Sridhar

Thanks,
Sridhar

Regards,
Sridhar Seshadri
Senior Director, Global Client Partner(Microsoft Alliance)


[cid:image001.jpg@01D67710.E72B3940]<http://www.terawe.com/>
YOUR DIGITAL TRANSFORMATION PARTNER
12503 Bel-Red Rd, ST 201, Bellevue, WA - 98005
Sridhar@terawe.com<mailto:Sridhar@terawe.com>
www.terawe.com<http://www.terawe.com/>
(m)425-436-4761
Terawe- Customer First, Delivery Excellence, Trust & Integrity, Fun Place to Work

[cid:image002.png@01D67710.E72B3940]

**Comment by daronyondem** [comment]
This is what we received from @SridharTerawe 

[20200823-Process Package for Power AppsV1.0.docx](https://github.com/microsoft/Azure-Analytics-and-AI-Engagement/files/5116154/20200823-Process.Package.for.Power.AppsV1.0.docx)

It looks like this process has to be manually done by the customer. Any objections?

**Comment by xor-ranavikrant** [comment]
Doesn't look like we have anything to automate with this issue then.

**Comment by SridharTerawe** [comment]
Yes you are right. Most of the Power Apps customer configurations have  to be done by customers are through the help of a partner this include, designing Power Apps screens, connection to the customer Power BI and PostgreSQL, MYSql, and SQL database etc.
