### ISSUE TITLE
Discover artifact types

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#74]

**Comment by daronyondem** [comment]
These might be static files, videos or GIFs. Needs to be investigated.

- Factory Heatmap
- Factory Floor View
- Azure Synapse Link animation
- Azure Synapse Link video

**Comment by xor-ranavikrant** [comment]
Have added all the website assets from storage into github repo including the videos we previously uploaded on soliance public storage. Largest file is 80Mb video, the complete folder is around 370 mb. So we can keep it all in repo if we choose to. And only move the files larger than 100mb to the public storage.
