### ISSUE TITLE
QA Notebooks in Synapse

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#76]

**Comment by daronyondem** [comment]
Here is the list of notebooks used in Synapse, that are found in the DEMO video.

- MFG_WITHOUT_HTAP
- MFG_WITH_HTAP
- 8a MFG Cosmos...
- 1 Prepare data for Predictive Maintenance in Synapse
- 3 Prepare Data for Product Anomaly Detection in Synapse

**Comment by daronyondem** [comment]
@xor-ranavikrant Once we have all dependencies in place don't we need a final round of QA for notebooks?

The `8a MFG Cosmos` notebook was shown in the DEMO video, but we can't find it. Out of scope.

**Comment by daronyondem** [comment]
Here is the link for the file from the solliance subscription https://solliancepublicdata.blob.core.windows.net/cdp/manufacturing-csv/telemetryp.csv

**Comment by xor-ranavikrant** [comment]
Getting the following error while running the notebooks:1 Prepare data for Predictive Maintenance in Synapse and 2 Prepare data for anomaly in Synapse
`AnalysisException : 'java.lang.RuntimeException: Operation failed: "This request is not authorized to perform this operation using this permission.", 403, HEAD, https://dreamdemostrggen2r16gxwb.dfs.core.windows.net/tempdata/tmp/hive?upn=false&action=getStatus&timeout=90;'`
@tshrivasdsd  could you suggest what the problem could be.

**Comment by sanjaydatasciencedojo** [comment]
Hi Rana,

It seems like permission issue. We will need to provide "Storage Blob 
Contributor"  access to that user for that storage.

Thanks,

Sanjay


------------------------------------------------------------------------
*From:* Xor-Ranavikrant <notifications@github.com>
*Sent:* Tuesday, August 25, 2020 3:36AM
*To:* Microsoft/azure-Analytics-And-Ai-Engagement 
<Azure-Analytics-and-AI-Engagement@noreply.github.com>
*Cc:* Sanjaydatasciencedojo <sanjay@datasciencedojo.com>, Mention 
<mention@noreply.github.com>
*Subject:* Re: [microsoft/Azure-Analytics-and-AI-Engagement] QA 
Notebooks in Synapse (#76)

**Comment by daronyondem** [comment]
Decision from meeting 8/25 9PM UTC

These four notebooks will be uploaded as they are with no modification.

![image](https://user-images.githubusercontent.com/2984187/91222181-7885d900-e727-11ea-8e30-7cfcbf6a54c1.png)
