### ISSUE TITLE
Figure out CosmosDB to PowerBI Dataset connection automation

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#77]

**Comment by xor-ranavikrant** [comment]
Cosmos Datasource connection update is not supported by the api yet, and somehow it is failing in updating the connection even for sql datasource where there are more than one connections.

**Comment by daronyondem** [comment]
What reports are depending on CosmosDB? As of our meeting on  8/24, Sanjay decided to take CosmosDB to second priority, not in scope for Phase 1. What reports do we have to take out of scope?
