### ISSUE TITLE
Cognitive search to be replicated or not?

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#81]
We are told that the web app is using a cognitive search service. We are not sure what the use is for. Any ideas @santosh-3e ?

**Comment by santosh-3e** [comment]
![image](https://user-images.githubusercontent.com/9485487/91228202-7c285880-e745-11ea-9c04-264fd37432ee.png)

We have configured twitter analytics function to use cognitive search. Endpoint - https://tweeter-text-analytics.cognitiveservices.azure.com/ is hosted in - CDP-VISION-DEMO-RG  in Spektra env.
